### ISSUE TITLE
数据流connect规则流之后，KeyedBroadcastProcessFunction触发不了ontimer的问题

### ISSUE THREAD

**Issue by usb098** [luxiaoxun/eagle#7]
我设置了事件时间env.setStreamTimeCharacteristic(TimeCharacteristic.EventTime);
数据流上也分配了水位线
但是DynamicAlertFunction中一直触发不了ontimer事件，后台日志打印出来，发现水位线一直是-9223372036854775808
有什么原因导致了这个问题呢

**Comment by usb098** [comment]
1.11版本不同的水位线策略，事件时间的会有问题。。。

**Comment by luxiaoxun** [comment]
> 1.11版本不同的水位线策略，事件时间的会有问题。。。

这个怎么理解？

**Comment by usb098** [comment]
> > 1.11版本不同的水位线策略，事件时间的会有问题。。。
> 
> 这个怎么理解？

这个是我代码写错了，规则流的水位线给去掉了导致的
